
/*TABLE UTILISATEUR*/
ALTER TABLE UTILISATEURS ADD CONSTRAINT pk_utilisateur PRIMARY KEY(id_user);
ALTER TABLE UTILISATEURS ADD CONSTRAINT fk_couple_utilisateur FOREIGN KEY(couple_id_user) 
REFERENCES UTILISATEURS(id_user) ON DELETE CASCADE;
ALTER TABLE UTILISATEURS ADD CONSTRAINT ck_sexe CHECK (sexe='M' OR sexe='F');
ALTER TABLE UTILISATEURS ADD CONSTRAINT un_tel UNIQUE (tel);
ALTER TABLE UTILISATEURS ADD CONSTRAINT un_email UNIQUE (email);


/* TABLE GROUPE */
ALTER TABLE GROUPES ADD CONSTRAINT pk_groupe PRIMARY KEY(id_groupe);
ALTER TABLE GROUPES ADD CONSTRAINT fk_groupe_user FOREIGN KEY(id_user) REFERENCES UTILISATEURS(id_user) 
			ON DELETE CASCADE;
ALTER TABLE GROUPES ADD CONSTRAINT un_nom_g UNIQUE(nom_groupe);
ALTER TABLE GROUPES ADD CONSTRAINT ck_type_g CHECK (type_groupe='prive' OR type_groupe='public');



/* TABLE PAGE */
ALTER TABLE PAGES ADD CONSTRAINT pk_page PRIMARY KEY(id_page);
ALTER TABLE PAGES ADD CONSTRAINT fk_page_user FOREIGN KEY(id_user) REFERENCES UTILISATEURS(id_user) 
			ON DELETE CASCADE;
ALTER TABLE PAGES ADD CONSTRAINT un_nom_p UNIQUE(nom_page);
ALTER TABLE PAGES ADD CONSTRAINT ck_type_p CHECK (type_page='prive' OR type_page='public');

/* TABLE PUBLICATION*/
ALTER TABLE PUBLICATIONS ADD CONSTRAINT pk_pub PRIMARY KEY(id_pub);
ALTER TABLE PUBLICATIONS ADD CONSTRAINT un_titre_pub UNIQUE(titre_pub);
ALTER TABLE PUBLICATIONS ADD CONSTRAINT fk_pub_user FOREIGN KEY(id_user) REFERENCES UTILISATEURS(id_user);
ALTER TABLE PUBLICATIONS ADD CONSTRAINT fk_pub_page FOREIGN KEY(id_page) REFERENCES PAGES(id_page);
ALTER TABLE PUBLICATIONS ADD CONSTRAINT fk_pub_groupe FOREIGN KEY(id_groupe) REFERENCES GROUPES(id_groupe);


/* TABLE AIMER PAGE */
ALTER TABLE PAGE_AIMES ADD CONSTRAINT pk_aimer_page_user PRIMARY KEY(id_user, id_page);
ALTER TABLE PAGE_AIMES ADD CONSTRAINT fk_aimer_page_user FOREIGN KEY(id_user) REFERENCES UTILISATEURS(id_user) 
			ON DELETE CASCADE;
ALTER TABLE PAGE_AIMES ADD CONSTRAINT fk_aimer_page_page FOREIGN KEY(id_page) REFERENCES PAGES(id_page) 
			ON DELETE CASCADE;

/* TABLE AIMER PUBLICATION */
ALTER TABLE PUBLICATION_AIMES ADD CONSTRAINT pk_aimer_pub_user PRIMARY KEY(id_user, id_pub);
ALTER TABLE PUBLICATION_AIMES ADD CONSTRAINT fk_aimer_pub_user FOREIGN KEY(id_user) REFERENCES UTILISATEURS(id_user) 
			ON DELETE CASCADE;
ALTER TABLE PUBLICATION_AIMES ADD CONSTRAINT fk_aimer_pub_pub FOREIGN KEY(id_page) REFERENCES PUBLICATIONS(id_page) 
			ON DELETE CASCADE;
	
/* TABLE ETRE_AMI */
ALTER TABLE AMITIES ADD CONSTRAINT pk_etre_ami PRIMARY KEY(id_user,ami_id_user) ;
ALTER TABLE AMITIES ADD CONSTRAINT fk_etre_ami_1 FOREIGN KEY(id_user) REFERENCES UTILISATEURS(id_user) ON DELETE CASCADE;
ALTER TABLE AMITIES ADD CONSTRAINT fk_etre_ami_2 FOREIGN KEY(ami_id_user) REFERENCES UTILISATEURS(id_user) ON DELETE CASCADE;

/* TABLE TCHATER */
ALTER TABLE TCHATS ADD CONSTRAINT pk_tchater_1 PRIMARY KEY(id_user_1, id_user_2) ;
ALTER TABLE TCHATS ADD CONSTRAINT fk_tchater_1 FOREIGN KEY(id_user_1) REFERENCES UTILISATEURS(id_user) ON DELETE CASCADE;
ALTER TABLE TCHATS ADD CONSTRAINT fk_tchater_2 FOREIGN KEY(id_user_2) REFERENCES UTILISATEURS(id_user) ON DELETE CASCADE;

/* TABLE INTEGRER*/
ALTER TABLE INTEGRATIONS ADD CONSTRAINT pk_integrer_user PRIMARY KEY(id_user, id_groupe);
ALTER TABLE INTEGRATIONS ADD CONSTRAINT fk_integrer_user FOREIGN KEY(id_user) REFERENCES UTILISATEURS(id_user) 
		ON DELETE CASCADE;
ALTER TABLE INTEGRATIONS ADD CONSTRAINT fk_integrer_groupe FOREIGN KEY(id_groupe) REFERENCES GROUPES(id_groupe) 
		ON DELETE CASCADE;

/* POSTER 
ALTER TABLE POSTS_GROUPE ADD CONSTRAINT pk_poster_user PRIMARY KEY(id_user, id_groupe, id_pub);
ALTER TABLE POSTS_GROUPE ADD CONSTRAINT fk_integrer_user FOREIGN KEY(id_user) REFERENCES UTILISATEURS(id_user) 
		ON DELETE CASCADE;
ALTER TABLE POSTS_GROUPE ADD CONSTRAINT fk_integrer_groupe FOREIGN KEY(id_groupe) REFERENCES GROUPES(id_groupe) 
		ON DELETE CASCADE;
ALTER TABLE POSTS_GROUPE ADD CONSTRAINT fk_integrer_pub FOREIGN KEY(id_pub) REFERENCES PUBLICATIONS(id_pub) 
		ON DELETE CASCADE;*/

/* ECRIRE 
ALTER TABLE POSTS_PAGE ADD CONSTRAINT pk_ecrire_user PRIMARY KEY(id_user, id_pub, id_page);
ALTER TABLE POSTS_PAGE ADD CONSTRAINT fk_ecrire_user FOREIGN KEY(id_user) REFERENCES UTILISATEURS(id_user) ON DELETE CASCADE;
ALTER TABLE POSTS_PAGE ADD CONSTRAINT fk_ecrire_page FOREIGN KEY(id_page) REFERENCES PAGES(id_page) ON DELETE CASCADE;
ALTER TABLE POSTS_PAGE ADD CONSTRAINT fk_ecrire_pub FOREIGN KEY(id_pub) REFERENCES PUBLICATIONS(id_pub) ON DELETE CASCADE;
*/

/* TABLE REPONDRE */
ALTER TABLE REPONSES ADD CONSTRAINT pk_repondre PRIMARY KEY(id_pub_1);
ALTER TABLE REPONSES ADD CONSTRAINT fk_pub_1 FOREIGN KEY(id_pub_1) REFERENCES PUBLICATIONS(id_pub) ON DELETE CASCADE;
ALTER TABLE REPONSES ADD CONSTRAINT fk_pub_2 FOREIGN KEY(id_pub_2) REFERENCES PUBLICATIONS(id_pub) ON DELETE CASCADE;

/* TABLE ETRE_AMI */
ALTER TABLE COUPLES ADD CONSTRAINT pk_couple PRIMARY KEY(id_user couple_id_user) ;
ALTER TABLE COUPLES ADD CONSTRAINT fk_couple_1 FOREIGN KEY(id_user) REFERENCES UTILISATEURS(id_user) ON DELETE CASCADE;
ALTER TABLE COUPLES ADD CONSTRAINT fk_couple_2 FOREIGN KEY(couple_id_user) REFERENCES UTILISATEURS(id_user) ON DELETE CASCADE;
